# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'transmission.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.ApplicationModal)
        MainWindow.resize(1748, 1008)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.title = QLabel(self.centralwidget)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(170, 20, 732, 33))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(Qt.LeftToRight)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 100, 541, 821))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.groupBox.setFont(font1)
        self.groupBox.setContextMenuPolicy(Qt.CustomContextMenu)
        self.groupBox.setLayoutDirection(Qt.LeftToRight)
        self.search_image = QPushButton(self.groupBox)
        self.search_image.setObjectName(u"search_image")
        self.search_image.setGeometry(QRect(140, 230, 161, 31))
        self.search_image.setFont(font1)
        self.image_source = QTextEdit(self.groupBox)
        self.image_source.setObjectName(u"image_source")
        self.image_source.setGeometry(QRect(30, 170, 411, 31))
        self.image_source.setFont(font1)
        self.select_image_label = QLabel(self.groupBox)
        self.select_image_label.setObjectName(u"select_image_label")
        self.select_image_label.setGeometry(QRect(160, 120, 161, 41))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setWeight(75)
        self.select_image_label.setFont(font2)
        self.select_image_label.setLayoutDirection(Qt.LeftToRight)
        self.image_parameters = QGroupBox(self.groupBox)
        self.image_parameters.setObjectName(u"image_parameters")
        self.image_parameters.setGeometry(QRect(20, 640, 501, 91))
        self.image_size = QTextEdit(self.image_parameters)
        self.image_size.setObjectName(u"image_size")
        self.image_size.setGeometry(QRect(250, 40, 104, 31))
        self.image_height = QTextEdit(self.image_parameters)
        self.image_height.setObjectName(u"image_height")
        self.image_height.setGeometry(QRect(130, 40, 104, 31))
        self.select_image_label_5 = QLabel(self.image_parameters)
        self.select_image_label_5.setObjectName(u"select_image_label_5")
        self.select_image_label_5.setGeometry(QRect(160, 0, 81, 41))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setWeight(75)
        self.select_image_label_5.setFont(font3)
        self.select_image_label_5.setLayoutDirection(Qt.LeftToRight)
        self.image_width_label = QLabel(self.image_parameters)
        self.image_width_label.setObjectName(u"image_width_label")
        self.image_width_label.setGeometry(QRect(40, 0, 81, 41))
        self.image_width_label.setFont(font3)
        self.image_width_label.setLayoutDirection(Qt.LeftToRight)
        self.select_image_label_6 = QLabel(self.image_parameters)
        self.select_image_label_6.setObjectName(u"select_image_label_6")
        self.select_image_label_6.setGeometry(QRect(280, 0, 81, 41))
        self.select_image_label_6.setFont(font3)
        self.select_image_label_6.setLayoutDirection(Qt.LeftToRight)
        self.image_width = QTextEdit(self.image_parameters)
        self.image_width.setObjectName(u"image_width")
        self.image_width.setGeometry(QRect(10, 40, 104, 31))
        self.select_image_label_11 = QLabel(self.image_parameters)
        self.select_image_label_11.setObjectName(u"select_image_label_11")
        self.select_image_label_11.setGeometry(QRect(370, 0, 121, 41))
        self.select_image_label_11.setFont(font3)
        self.select_image_label_11.setLayoutDirection(Qt.LeftToRight)
        self.image_bpp = QTextEdit(self.image_parameters)
        self.image_bpp.setObjectName(u"image_bpp")
        self.image_bpp.setGeometry(QRect(370, 40, 104, 31))
        self.color_space = QComboBox(self.groupBox)
        self.color_space.addItem("")
        self.color_space.addItem("")
        self.color_space.setObjectName(u"color_space")
        self.color_space.setGeometry(QRect(260, 50, 151, 31))
        font4 = QFont()
        font4.setPointSize(12)
        self.color_space.setFont(font4)
        self.select_image_label_4 = QLabel(self.groupBox)
        self.select_image_label_4.setObjectName(u"select_image_label_4")
        self.select_image_label_4.setGeometry(QRect(70, 40, 161, 41))
        self.select_image_label_4.setFont(font2)
        self.select_image_label_4.setLayoutDirection(Qt.LeftToRight)
        self.image_label = QLabel(self.groupBox)
        self.image_label.setObjectName(u"image_label")
        self.image_label.setGeometry(QRect(90, 300, 411, 251))
        self.image_box = QGroupBox(self.centralwidget)
        self.image_box.setObjectName(u"image_box")
        self.image_box.setGeometry(QRect(600, 100, 561, 851))
        self.image_box.setFont(font1)
        self.image_box.setContextMenuPolicy(Qt.CustomContextMenu)
        self.image_box.setLayoutDirection(Qt.LeftToRight)
        self.decomposition_levels = QSpinBox(self.image_box)
        self.decomposition_levels.setObjectName(u"decomposition_levels")
        self.decomposition_levels.setGeometry(QRect(280, 70, 121, 31))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(True)
        font5.setWeight(75)
        self.decomposition_levels.setFont(font5)
        self.decomposition_levels.setMinimum(1)
        self.decomposition_levels.setMaximum(4)
        self.wavelet_dec = QPushButton(self.image_box)
        self.wavelet_dec.setObjectName(u"wavelet_dec")
        self.wavelet_dec.setGeometry(QRect(110, 280, 231, 31))
        self.wavelet_dec.setFont(font1)
        self.select_image_label_2 = QLabel(self.image_box)
        self.select_image_label_2.setObjectName(u"select_image_label_2")
        self.select_image_label_2.setGeometry(QRect(40, 60, 211, 41))
        self.select_image_label_2.setFont(font3)
        self.select_image_label_2.setLayoutDirection(Qt.LeftToRight)
        self.DWT_type = QComboBox(self.image_box)
        self.DWT_type.addItem("")
        self.DWT_type.addItem("")
        self.DWT_type.addItem("")
        self.DWT_type.addItem("")
        self.DWT_type.addItem("")
        self.DWT_type.addItem("")
        self.DWT_type.setObjectName(u"DWT_type")
        self.DWT_type.setGeometry(QRect(230, 130, 281, 31))
        font6 = QFont()
        font6.setPointSize(11)
        self.DWT_type.setFont(font6)
        self.DWT_type_label = QLabel(self.image_box)
        self.DWT_type_label.setObjectName(u"DWT_type_label")
        self.DWT_type_label.setGeometry(QRect(40, 120, 231, 41))
        self.DWT_type_label.setFont(font3)
        self.DWT_type_label.setLayoutDirection(Qt.LeftToRight)
        self.DWT_type_label_2 = QLabel(self.image_box)
        self.DWT_type_label_2.setObjectName(u"DWT_type_label_2")
        self.DWT_type_label_2.setGeometry(QRect(40, 180, 231, 41))
        self.DWT_type_label_2.setFont(font3)
        self.DWT_type_label_2.setLayoutDirection(Qt.LeftToRight)
        self.wavelet_type = QComboBox(self.image_box)
        self.wavelet_type.addItem("")
        self.wavelet_type.addItem("")
        self.wavelet_type.addItem("")
        self.wavelet_type.setObjectName(u"wavelet_type")
        self.wavelet_type.setGeometry(QRect(220, 190, 201, 31))
        self.wavelet_type.setFont(font6)
        self.wavelet_label = QLabel(self.image_box)
        self.wavelet_label.setObjectName(u"wavelet_label")
        self.wavelet_label.setGeometry(QRect(30, 360, 511, 401))
        self.wavelet_label.setMaximumSize(QSize(16777215, 16777215))
        self.wavelet_parameters = QGroupBox(self.image_box)
        self.wavelet_parameters.setObjectName(u"wavelet_parameters")
        self.wavelet_parameters.setGeometry(QRect(450, 370, 111, 411))
        self.wavelet_width = QTextEdit(self.wavelet_parameters)
        self.wavelet_width.setObjectName(u"wavelet_width")
        self.wavelet_width.setGeometry(QRect(0, 40, 104, 31))
        self.image_width_label_2 = QLabel(self.wavelet_parameters)
        self.image_width_label_2.setObjectName(u"image_width_label_2")
        self.image_width_label_2.setGeometry(QRect(30, 0, 81, 41))
        self.image_width_label_2.setFont(font3)
        self.image_width_label_2.setLayoutDirection(Qt.LeftToRight)
        self.wavelet_height = QTextEdit(self.wavelet_parameters)
        self.wavelet_height.setObjectName(u"wavelet_height")
        self.wavelet_height.setGeometry(QRect(0, 120, 104, 31))
        self.image_width_label_3 = QLabel(self.wavelet_parameters)
        self.image_width_label_3.setObjectName(u"image_width_label_3")
        self.image_width_label_3.setGeometry(QRect(30, 80, 81, 41))
        self.image_width_label_3.setFont(font3)
        self.image_width_label_3.setLayoutDirection(Qt.LeftToRight)
        self.wavelet_size = QTextEdit(self.wavelet_parameters)
        self.wavelet_size.setObjectName(u"wavelet_size")
        self.wavelet_size.setGeometry(QRect(0, 200, 104, 31))
        self.image_width_label_4 = QLabel(self.wavelet_parameters)
        self.image_width_label_4.setObjectName(u"image_width_label_4")
        self.image_width_label_4.setGeometry(QRect(30, 160, 81, 41))
        self.image_width_label_4.setFont(font3)
        self.image_width_label_4.setLayoutDirection(Qt.LeftToRight)
        self.wavelet_time = QTextEdit(self.wavelet_parameters)
        self.wavelet_time.setObjectName(u"wavelet_time")
        self.wavelet_time.setGeometry(QRect(0, 280, 104, 31))
        self.image_width_label_5 = QLabel(self.wavelet_parameters)
        self.image_width_label_5.setObjectName(u"image_width_label_5")
        self.image_width_label_5.setGeometry(QRect(30, 240, 81, 41))
        self.image_width_label_5.setFont(font3)
        self.image_width_label_5.setLayoutDirection(Qt.LeftToRight)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(1210, 100, 511, 851))
        self.groupBox_2.setFont(font1)
        self.groupBox_3 = QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(30, 40, 461, 241))
        self.loops = QSpinBox(self.groupBox_2)
        self.loops.setObjectName(u"loops")
        self.loops.setGeometry(QRect(310, 300, 121, 31))
        self.loops.setFont(font5)
        self.loops.setMinimum(1)
        self.loops.setMaximum(10)
        self.select_image_label_3 = QLabel(self.groupBox_2)
        self.select_image_label_3.setObjectName(u"select_image_label_3")
        self.select_image_label_3.setGeometry(QRect(70, 290, 221, 41))
        self.select_image_label_3.setFont(font3)
        self.select_image_label_3.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1748, 26))
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)

        self.color_space.setCurrentIndex(0)
        self.DWT_type.setCurrentIndex(0)
        self.wavelet_type.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.title.setText(QCoreApplication.translate("MainWindow", u"Data Transmission using EZW Algorithm - Transmitter", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Image", None))
        self.search_image.setText(QCoreApplication.translate("MainWindow", u"Search and Load", None))
        self.select_image_label.setText(QCoreApplication.translate("MainWindow", u"Select image", None))
        self.image_parameters.setTitle("")
        self.select_image_label_5.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.image_width_label.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.select_image_label_6.setText(QCoreApplication.translate("MainWindow", u"Size", None))
        self.select_image_label_11.setText(QCoreApplication.translate("MainWindow", u"Bits per pixel ", None))
        self.color_space.setItemText(0, QCoreApplication.translate("MainWindow", u"Grayscale", None))
        self.color_space.setItemText(1, QCoreApplication.translate("MainWindow", u"RGB", None))

        self.select_image_label_4.setText(QCoreApplication.translate("MainWindow", u"Color space", None))
        self.image_label.setText("")
        self.image_box.setTitle(QCoreApplication.translate("MainWindow", u"Wavelet Decomposition Transform", None))
        self.wavelet_dec.setText(QCoreApplication.translate("MainWindow", u"Wavelet Decomposition", None))
        self.select_image_label_2.setText(QCoreApplication.translate("MainWindow", u"Decomposition Levels", None))
        self.DWT_type.setItemText(0, QCoreApplication.translate("MainWindow", u"PyWavelets", None))
        self.DWT_type.setItemText(1, QCoreApplication.translate("MainWindow", u"Convolution - SingleThread", None))
        self.DWT_type.setItemText(2, QCoreApplication.translate("MainWindow", u"Convolution - MultiThread", None))
        self.DWT_type.setItemText(3, QCoreApplication.translate("MainWindow", u"Linear-Based - SingleThread", None))
        self.DWT_type.setItemText(4, QCoreApplication.translate("MainWindow", u"Linear-Based - MultiThread", None))
        self.DWT_type.setItemText(5, "")

        self.DWT_type_label.setText(QCoreApplication.translate("MainWindow", u"Transform type", None))
        self.DWT_type_label_2.setText(QCoreApplication.translate("MainWindow", u"Wavelet type", None))
        self.wavelet_type.setItemText(0, QCoreApplication.translate("MainWindow", u"Haar", None))
        self.wavelet_type.setItemText(1, QCoreApplication.translate("MainWindow", u"Biorthogonal", None))
        self.wavelet_type.setItemText(2, QCoreApplication.translate("MainWindow", u"Daubechies-1", None))

        self.wavelet_label.setText("")
        self.wavelet_parameters.setTitle("")
        self.image_width_label_2.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.image_width_label_3.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.image_width_label_4.setText(QCoreApplication.translate("MainWindow", u"Size", None))
        self.image_width_label_5.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Encoding and Sending", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.select_image_label_3.setText(QCoreApplication.translate("MainWindow", u"Thresholding Iterations", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

